version: '3.8'

services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - proje-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Clarusway_1'
      MYSQL_USER: 'clarusway'
      MYSQL_PASSWORD: 'Clarusway_1'
      MYSQL_DATABASE: 'bookstore_db'
    networks:
      - mysqlnet

  appserver:
    build: .
    depends_on:
      - database
    ports:
      - "80:80"
    restart: always
    networks:
      - mysqlnet
    
volumes:
  proje-vol:

networks:
  mysqlnet:
    driver: bridge